---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: docs/docs
  label: Docs
  create: documents
  match: "**/*"
  templates:
  - debugging
upload_dir: docs/docs/images
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
custom_preview: true
build:
  preview_command: npm run build
  output_directory: public
